version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: bdblogapi
    ports:
      - "5906:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8584:80
    depends_on:
      - db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      PMA_USER: root
      PMA_HOST: db
      
  app:
    image: php:8.0-apache
    container_name: appweb
    depends_on:
      - phpmyadmin
    volumes:
      - ./:/var/www/html/
    ports:
      - "8502:80"
    stdin_open: true
    tty: true   